### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by danielf** [ef363/FFT#5]
Enough said. https://docs.python.org/2/library/unittest.html

**Comment by ef363** [comment]
We've changed up our unit testing quite a bit:
1. Switched to numpy. Now we test our FFT by comparing it to numpy's version, instead of comparing it to our DFT.
2. Using numpy.allclose to determine whether two arrays are "almost equal", instead of defining our own "almostEqualArrays" function inside the test file.
3. Reorganized the test suite and runner for brevity.

Daniel, do you have any other suggestions for us regarding unit testing?

**Comment by danielf** [comment]
As mentioned during lunch today, you can use FFT to test itself by generating random inputs, doing FFT, then the inverse FFT (http://en.wikipedia.org/wiki/Discrete_Fourier_transform#Expressing_the_inverse_DFT_in_terms_of_the_DFT) and compare the returning vector to the original one. Of course this is not a complete test as the identity function would work also, but it's a good test to check for numerical stability.

**Comment by daveckman** [comment]
We added the TestFFTandIFFT unit testing class which first runs FFT and then runs IFFT on the output of FFT. The unit tests check if the result matches the random input vector.
